#application: search-party
application: schpty
version: dev
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: css

- url: /imgs
  static_dir: imgs

- url: /js
  static_dir: js

- url: .*
  script: main.py
