#application: search-party
application: schpty
version: dev
runtime: python
api_version: 1

inbound_services:
- channel_presence

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /css
  static_dir: css

- url: /imgs
  static_dir: imgs

- url: /js
  static_dir: js

- url: .*
  script: main.py
 
builtins:
- appstats: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.zip$
- ^(.*/)?.*\.swp$
- ^(.*/)?.*\.swo$
- ^(.*/)?.*\.pptx$
- ^(.*/)?.*\.ppt$
- ^(.*/)?.*\.bat$
- ^(.*/)?.*\.txt$
- ^(.*[^a-zA-Z])?delme[^a-zA-Z].*
- ^(.*/)?junk/.+
- ^(.*/)?scripts/.+
- ^(.*/)?templatetags/.*
- ^(.*/)?js/graph/.*\.html$
- ^(.*/)?js/graph/example\.js$
- ^(.*/)?\.svn/.*
